trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pylint src/
  displayName: 'Lint source code'

- script: |
    pytest tests/unit
    pytest tests/integration
  displayName: 'Run tests'
